# Generated by Django 3.2.4 on 2023-11-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='User',
        ),
    ]
