# Generated by Django 4.2.6 on 2023-11-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0003_auto_20231107_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='teste.genre'),
        ),
    ]
