# Generated by Django 4.2.6 on 2023-11-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0004_genre_delete_genres_game_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isAvailableToRent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
