# Generated by Django 4.2.6 on 2023-11-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0005_game_isavailabletorent_game_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='isAvailableToRent',
            field=models.BooleanField(),
        ),
    ]
