# Generated by Django 4.2.6 on 2023-11-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0006_alter_game_isavailabletorent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
