# Generated by Django 4.2.6 on 2023-11-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0007_alter_game_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='allowsSimultaneousRentals',
        ),
        migrations.AddField(
            model_name='platform',
            name='logo',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
