# Generated by Django 4.2.6 on 2023-11-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0008_remove_platform_allowssimultaneousrentals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
