# Generated by Django 4.2.6 on 2023-11-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
