# Generated by Django 3.2.4 on 2023-11-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact',
            new_name='phone',
        ),
    ]
