# Generated by Django 3.2.4 on 2023-12-11 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_game_cover_alter_platform_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='textColor',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
