# Generated by Django 4.2.7 on 2023-12-11 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_notification_user_notification_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.game'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_sender',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
