# Generated by Django 4.2.7 on 2023-12-11 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_notification_user_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
