# Generated by Django 4.2.7 on 2023-12-11 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_notification_user_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='game',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_receiver',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_sender',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
