# Generated by Django 3.2.4 on 2023-12-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalmanager',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
