# Generated by Django 3.2.4 on 2023-12-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_paymentmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentManager',
        ),
    ]
